# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('shirt_size', models.CharField(choices=[('XS', 'EXTRA-SMALL'), ('S', 'SMALL'), ('M', 'MEDIUM'), ('L', 'LARGE'), ('XL', 'EXTRA-LARGE'), ('XXL', 'XX-LARGE'), ('XXXL', 'Vin_Diesel'), ('None', 'None')], max_length=4)),
                ('abstract', models.TextField(max_length=2400)),
                ('presentation', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=3)),
                ('funding_source', models.CharField(max_length=10)),
                ('roommate_pref', models.CharField(max_length=100)),
                ('vegetarian', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=3)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BMB_Registration.PI')),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(max_length=50)),
                ('variable_value', models.CharField(max_length=300)),
            ],
        ),
    ]
