# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(blank=True, default='', max_length=500)),
                ('abstract', models.TextField(max_length=2400)),
                ('poster_number', models.IntegerField(blank=True, null=True)),
                ('scores', models.CharField(blank=True, max_length=30, null=True)),
                ('PI', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BMB_Registration.PI')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='', max_length=6)),
                ('position', models.CharField(choices=[('student', 'student'), ('postdoc', 'postdoc'), ('faculty', 'faculty'), ('staff', 'staff')], default='', max_length=7)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('shirt_size', models.CharField(choices=[('XS', 'EXTRA-SMALL'), ('S', 'SMALL'), ('M', 'MEDIUM'), ('L', 'LARGE'), ('XL', 'EXTRA-LARGE'), ('XXL', 'XX-LARGE'), ('XXXL', 'Vin_Diesel'), ('None', 'None')], max_length=4)),
                ('presentation', models.CharField(choices=[('poster', 'poster'), ('talk', 'talk'), ('decline', 'decline')], default='decline', help_text='Years 3 and above must present a poster.', max_length=7)),
                ('funding_source', models.CharField(max_length=10)),
                ('stay_at_hotel', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=3)),
                ('share_room', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=3)),
                ('roommate_pref', models.CharField(blank=True, max_length=100)),
                ('vegetarian', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=3)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BMB_Registration.Department')),
                ('lab', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='BMB_Registration.PI')),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(max_length=50)),
                ('variable_value', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BMB_Registration.User'),
        ),
    ]
