# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BMB_Registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lab',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='BMB_Registration.PI'),
        ),
    ]
