# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMB_Registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='avg_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
