# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMB_Registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pi',
            options={'verbose_name': 'PI', 'verbose_name_plural': 'PIs'},
        ),
        migrations.AddField(
            model_name='user',
            name='detailed_judges',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rank_judges',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
