# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BMB_Registration', '0002_auto_20170624_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField(max_length=2400)),
                ('PI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BMB_Registration.PI')),
                ('authors', models.ManyToManyField(to='BMB_Registration.Submission')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='abstract',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='', max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('student', 'student'), ('postdoc', 'postdoc'), ('faculty', 'faculty'), ('staff', 'staff')], default='', max_length=7),
        ),
        migrations.AddField(
            model_name='user',
            name='share_room',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='stay_at_hotel',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='presentation',
            field=models.CharField(choices=[('poster', 'poster'), ('talk', 'talk'), ('decline', 'decline')], default='decline', max_length=7),
        ),
        migrations.AlterField(
            model_name='user',
            name='roommate_pref',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BMB_Registration.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='BMB_Registration.Department'),
        ),
    ]
