# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BMB_Registration', '0002_auto_20170704_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='detailed_judges',
            new_name='detailed_posters',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='rank_judges',
            new_name='rank_posters',
        ),
    ]
