# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMB_Registration', '0002_submission_avg_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ('-avg_score',)},
        ),
        migrations.AddField(
            model_name='submission',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
