# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMB_Registration', '0003_auto_20170624_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
