# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMB_Registration', '0003_auto_20170704_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='assigned_ranks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
