# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMB_Registration', '0004_auto_20170624_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='pi',
            name='first_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
