# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMB_Registration', '0005_pi_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='authors',
        ),
        migrations.AddField(
            model_name='submission',
            name='authors',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='presentation',
            field=models.CharField(choices=[('poster', 'poster'), ('talk', 'talk'), ('decline', 'decline')], default='decline', help_text='Years 3 and above must present a poster.', max_length=7),
        ),
    ]
