# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BMB_Registration', '0006_auto_20170624_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='PI',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='BMB_Registration.PI'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='authors',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
