# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMB_Registration', '0007_user_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roommate_pref',
            field=models.CharField(blank=True, help_text='Optional', max_length=100),
        ),
    ]
