# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BMB_Registration', '0008_auto_20170721_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosterRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_set', models.PositiveSmallIntegerField()),
                ('rank', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='submission',
            name='poster_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='posterrank',
            name='poster_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BMB_Registration.Submission', to_field='poster_number'),
        ),
    ]
