# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMB_Registration', '0010_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shirt_size',
            field=models.CharField(choices=[('XS', 'EXTRA-SMALL'), ('S', 'SMALL'), ('M', 'MEDIUM'), ('L', 'LARGE'), ('XL', 'EXTRA-LARGE'), ('XXL', 'XX-LARGE'), ('XXXL', 'XXXL'), ('None', 'None')], max_length=4),
        ),
    ]
