# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 05:10
from __future__ import unicode_literals

import BMB_Registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMB_Registration', '0012_auto_20170823_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='upload',
            field=models.FileField(storage='E:\\MyStuff\\MyDocs\\BCM\\media\\uploads', upload_to=BMB_Registration.models.user_directory_path),
        ),
    ]
