# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-07-21 20:16
from __future__ import unicode_literals

import BMB_Registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMB_Registration', '0014_auto_20170823_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='final_author',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='submission',
            name='presenter',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='submission',
            name='abstract',
            field=models.TextField(help_text='For superscript, enter "$^{text}$".\n                                     For subscript, enter "$_{text}$".\n                                     For italics, enter "\\textit{text}".\n                                     For bold, enter "\\textbf{text}".\n                                     Greek letters can be entered directly.\n                                     ', max_length=3240),
        ),
        migrations.AlterField(
            model_name='upload',
            name='upload',
            field=models.FileField(upload_to=BMB_Registration.models.user_directory_path),
        ),
    ]
